"""CADKernel - Python bindings for the CADKernel B-Rep CAD kernel."""

from cadkernel._native import *  # noqa: F401, F403
from cadkernel._native import (
    # Classes
    Model,
    SolidHandle,
    VertexHandle,
    FaceHandle,
    Mesh,
    MassProperties,
    GeometryCheck,
    SectionEdge,
    TetMesh,
    FemResult,
    Assembly,
    Compound,
    Sketch,
)

__version__ = "0.1.0"
__all__ = [
    # Classes
    "Model",
    "SolidHandle",
    "VertexHandle",
    "FaceHandle",
    "Mesh",
    "MassProperties",
    "GeometryCheck",
    "SectionEdge",
    "TetMesh",
    "FemResult",
    "Assembly",
    "Compound",
    "Sketch",
    # Primitives
    "create_box",
    "create_cylinder",
    "create_sphere",
    "create_cone",
    "create_torus",
    "create_tube",
    "create_prism",
    "create_wedge",
    "create_ellipsoid",
    "create_helix",
    "create_spiral",
    "create_polygon",
    "create_plane_face",
    "create_gear",
    # Feature operations
    "extrude_profile",
    "revolve_profile",
    "mirror",
    "scale",
    "sweep_profile",
    "loft_profiles",
    "chamfer",
    "fillet",
    "shell",
    "pattern_linear",
    "pattern_circular",
    "pad_profile",
    "pocket_profile",
    "draft",
    "section",
    "split",
    "thickness",
    "taper",
    "offset",
    "groove_profile",
    "create_hole",
    "create_countersunk_hole",
    "cross_section",
    "reverse",
    "refine",
    "mesh_to_solid",
    # PartDesign additive/subtractive
    "pd_additive_box",
    "pd_subtractive_box",
    "pd_additive_cylinder",
    "pd_subtractive_cylinder",
    "pd_additive_sphere",
    "pd_subtractive_sphere",
    "pd_additive_cone",
    "pd_subtractive_cone",
    "pd_additive_torus",
    "pd_subtractive_torus",
    "pd_additive_helix",
    "pd_subtractive_helix",
    "pd_additive_ellipsoid",
    "pd_subtractive_ellipsoid",
    "pd_additive_prism",
    "pd_subtractive_prism",
    "pd_additive_wedge",
    "pd_subtractive_wedge",
    "pd_additive_loft",
    "pd_subtractive_loft",
    "pd_additive_pipe",
    "pd_subtractive_pipe",
    # Join operations
    "join_connect",
    "join_embed",
    "join_cutout",
    # Multi-transform
    "apply_multi_transform",
    # Boolean operations
    "boolean_union",
    "boolean_subtract",
    "boolean_intersect",
    "boolean_xor_op",
    # Tessellation & measurement
    "tessellate",
    "mass_properties",
    "geometry_check",
    "watertight_check",
    "dist_between_points",
    # Mesh operations
    "decimate",
    "mesh_fill_holes",
    "mesh_curvature",
    "mesh_subdivide",
    "mesh_flip_normals",
    "mesh_smooth",
    "mesh_union",
    "mesh_intersection",
    "mesh_difference",
    "mesh_cut_with_plane",
    "mesh_harmonize_normals",
    "mesh_is_watertight",
    "mesh_remesh",
    "mesh_scale",
    "mesh_repair",
    # FEM
    "fem_generate_tet_mesh",
    "fem_static_analysis",
    # I/O
    "export_stl",
    "export_stl_binary",
    "export_obj",
    "export_gltf",
    "export_step",
    "export_iges",
    "export_dxf",
    "export_ply",
    "export_3mf",
    "export_brep",
    "export_dae",
    "export_amf",
    "import_stl",
    "import_obj",
    "import_dxf",
    "import_ply",
    "import_3mf",
    "import_brep",
    "import_dae",
    "import_amf",
    "import_step",
    "import_iges",
    "save_project",
    "load_project",
]
