pub mod chamfer;
pub(crate) mod copy_utils;
pub mod draft;
pub mod extrude;
pub mod fillet;
pub mod loft;
pub mod mirror;
pub mod pattern;
pub mod revolve;
pub mod scale;
pub mod shell;
pub mod split;
pub mod sweep;

pub use chamfer::{ChamferResult, chamfer_edge};
pub use draft::{DraftResult, draft_faces};
pub use extrude::{ExtrudeResult, extrude};
pub use fillet::{FilletResult, fillet_edge};
pub use loft::{LoftResult, loft};
pub use mirror::{MirrorResult, mirror_solid};
pub use pattern::{PatternResult, circular_pattern, linear_pattern};
pub use revolve::{RevolveResult, revolve};
pub use scale::{ScaleResult, scale_solid};
pub use shell::{ShellResult, shell_solid};
pub use split::{SplitResult, split_solid};
pub use sweep::{SweepResult, sweep};
